name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

# ============================================
# ESTA ES LA LÍNEA NUEVA Y FUNDAMENTAL
# ============================================
permissions:
  contents: write
# ============================================

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Descarga el código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Reemplaza los marcadores
      - name: Replace Firebase config placeholders
        run: |
          for secret_name in API_KEY AUTH_DOMAIN PROJECT_ID STORAGE_BUCKET MESSAGING_SENDER_ID APP_ID MEASUREMENT_ID; do
            placeholder="__${secret_name}__"
            secret_value=$(eval echo "\$${secret_name}")
            perl -i -pe "s/\Q$placeholder\E/$secret_value/g" index.html
          done
        env:
          API_KEY: ${{ secrets.API_KEY }}
          AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }}
          MESSAGING_SENDER_ID: ${{ secrets.MESSAGING_SENDER_ID }}
          APP_ID: ${{ secrets.APP_ID }}
          MEASUREMENT_ID: ${{ secrets.MEASUREMENT_ID }}

      # 3. Despliega la carpeta a la rama 'gh-pages'
      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
