name: Deploy to GitHub Pages

on:
  # Se ejecuta cada vez que haces un push a la rama 'main'
  push:
    branches:
      - main
  # Te permite ejecutarlo manualmente desde la pestaña de Actions
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Descarga el código de tu repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Reemplaza los marcadores de posición con los secretos
      - name: Replace Firebase config placeholders
        run: |
          sed -i "s|__API_KEY__|${{ secrets.API_KEY }}|g" index.html
          sed -i "s|__AUTH_DOMAIN__|${{ secrets.AUTH_DOMAIN }}|g" index.html
          sed -i "s|__PROJECT_ID__|${{ secrets.PROJECT_ID }}|g" index.html
          sed -i "s|__STORAGE_BUCKET__|${{ secrets.STORAGE_BUCKET }}|g" index.html
          sed -i "s|__MESSAGING_SENDER_ID__|${{ secrets.MESSAGING_SENDER_ID }}|g" index.html
          sed -i "s|__APP_ID__|${{ secrets.APP_ID }}|g" index.html
          sed -i "s|__MEASUREMENT_ID__|${{ secrets.MEASUREMENT_ID }}|g" index.html

      # 3. Despliega la carpeta actual a la rama 'gh-pages'
      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
